- name: "Deploy Configuration"
  hosts: prod
  become: true
  vars:
    ansible_sudo_pass: admin
  pre_tasks: 
    - name: Install EPEL repository
      yum: name=epel-release state=present
      when: ansible_distribution == "CentOS"
    - name: install python-pip
      yum: name=python-pip state=present
    - name: Install docker python
      pip: name-docker-py
  tasks:
    - name: Create an apache container
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"

