- name: "Deploy Configuration"
  hosts: prod
  pre_tasks:
    - name: Install docker python
      pip: name-docker-py
  tasks:
    - name: Create an apache container
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"

