---
all: 
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
prod:
  hosts:
    client: 
      ansible_host: 10.0.36.5
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3

  